name: ci-mrs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '2.11.0/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          images: |
            khalibre/openmrs-reference
            ghcr.io/Khalibre/openmrs-reference
          tags: |
            type=raw,value=2.11.0
            type=raw,value=2.11.0-{{date 'YYYYMMDD' tz='Asia/Phnom_Penh'}}-${{ github.run_number }},enable=${{ github.event_name == 'push' && github.ref_type == 'branch' || github.event_name == 'workflow_dispatch' }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./2.11.0
          push: true
          load: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
