name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'base/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker
        uses: ./.github/workflows/docker-setup.yml
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          images: |
            khalibre/openmrs-tomcat-base
            ghcr.io/Khalibre/openmrs-tomcat-base
          tags: |
            type=raw,value=7-jdk8-jammy
            type=raw,value=7-jdk8-jammy-{{date 'YYYYMMDD' tz='Asia/Phnom_Penh'}}-${{ github.run_number }},enable=${{ github.event_name == 'push' && github.ref_type == 'branch' }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./base
          push: true
          load: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
